# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_pb2 as chat__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class Gemma4ServerStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.MakeRequest = channel.unary_unary(
                '/chat.Gemma4Server/MakeRequest',
                request_serializer=chat__pb2.Request.SerializeToString,
                response_deserializer=chat__pb2.Response.FromString,
                _registered_method=True)
        self.MakeRequestStreamBackTokenByToken = channel.unary_stream(
                '/chat.Gemma4Server/MakeRequestStreamBackTokenByToken',
                request_serializer=chat__pb2.Request.SerializeToString,
                response_deserializer=chat__pb2.Response.FromString,
                _registered_method=True)


class Gemma4ServerServicer:
    """Missing associated documentation comment in .proto file."""

    def MakeRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MakeRequestStreamBackTokenByToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_Gemma4ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'MakeRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.MakeRequest,
                    request_deserializer=chat__pb2.Request.FromString,
                    response_serializer=chat__pb2.Response.SerializeToString,
            ),
            'MakeRequestStreamBackTokenByToken': grpc.unary_stream_rpc_method_handler(
                    servicer.MakeRequestStreamBackTokenByToken,
                    request_deserializer=chat__pb2.Request.FromString,
                    response_serializer=chat__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.Gemma4Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.Gemma4Server', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Gemma4Server:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def MakeRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.Gemma4Server/MakeRequest',
            chat__pb2.Request.SerializeToString,
            chat__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MakeRequestStreamBackTokenByToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.Gemma4Server/MakeRequestStreamBackTokenByToken',
            chat__pb2.Request.SerializeToString,
            chat__pb2.Response.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
