# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\"1\n\x0fImageAttachment\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\x0c\x12\x10\n\x08mimeType\x18\x02 \x01(\t\"b\n\x07Message\x12\x0c\n\x04text\x18\x01 \x01(\t\x12\x19\n\x04role\x18\x02 \x01(\x0e\x32\x0b.chat.Roles\x12.\n\x0fimageAttachment\x18\x03 \x03(\x0b\x32\x15.chat.ImageAttachment\"*\n\x07History\x12\x1f\n\x08messages\x18\x01 \x03(\x0b\x32\r.chat.Message\"M\n\x07Request\x12\x1e\n\x07history\x18\x01 \x01(\x0b\x32\r.chat.History\x12\"\n\x0buserMessage\x18\x02 \x01(\x0b\x32\r.chat.Message\",\n\x08Response\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\x12\x10\n\x08thoughts\x18\x02 \x01(\t*=\n\x05Roles\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\n\n\x06SYSTEM\x10\x01\x12\x08\n\x04USER\x10\x02\x12\r\n\tASSISTANT\x10\x03\x32\x82\x01\n\x0cGemma4Server\x12,\n\x0bMakeRequest\x12\r.chat.Request\x1a\x0e.chat.Response\x12\x44\n!MakeRequestStreamBackTokenByToken\x12\r.chat.Request\x1a\x0e.chat.Response0\x01\x42\x07\xaa\x02\x04\x43hatb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\252\002\004Chat'
  _globals['_ROLES']._serialized_start=340
  _globals['_ROLES']._serialized_end=401
  _globals['_IMAGEATTACHMENT']._serialized_start=20
  _globals['_IMAGEATTACHMENT']._serialized_end=69
  _globals['_MESSAGE']._serialized_start=71
  _globals['_MESSAGE']._serialized_end=169
  _globals['_HISTORY']._serialized_start=171
  _globals['_HISTORY']._serialized_end=213
  _globals['_REQUEST']._serialized_start=215
  _globals['_REQUEST']._serialized_end=292
  _globals['_RESPONSE']._serialized_start=294
  _globals['_RESPONSE']._serialized_end=338
  _globals['_GEMMA4SERVER']._serialized_start=404
  _globals['_GEMMA4SERVER']._serialized_end=534
# @@protoc_insertion_point(module_scope)
